import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Local brand fonts
const walter = localFont({
  variable: "--font-walter",
  src: [
    { path: "../public/fonts/ABCWalterNeue-Extrafett.woff2", weight: "800", style: "normal" },
    { path: "../public/fonts/ABCWalterNeue-Normal.woff2", weight: "400", style: "normal" },
  ],
  display: "swap",
});

const simon = localFont({
  variable: "--font-simon",
  src: [
    { path: "../public/fonts/ABCSimonMono-Regular.woff2", weight: "400", style: "normal" },
    { path: "../public/fonts/ABCSimonMono-Medium.woff2", weight: "500", style: "normal" },
  ],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${walter.variable} ${simon.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
